name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - name: GCC
            cxx: g++

          - name: Clang
            cxx: clang++

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build g++ clang

      - name: Configure
        env:
          CXX: ${{ matrix.cxx }}
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: |
          cmake --build build --parallel

      - name: Run Tests
        run: |
          ctest --test-dir build --output-on-failure
