name: Clang Tidy

on:
  push:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy
        run: |
          sudo apt update
          sudo apt install -y clang-tidy

      - name: Configure cmake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_CLANG_TIDY=clang-tidy

      - name: Build
        run: cmake --build build
