name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create Github Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
