name: Release

on:
  push:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create Github Release
        uses: softprops/action-gh-release@v2


